name: Security scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  Security-scan-for-dependencies:
    runs-on: ubuntu-slim

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v5
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      # Bunをセットアップ
      - uses: oven-sh/setup-bun@v2

      # AikidoSec Safe Chainをセットアップ
      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      
      - name: Install dependencies
        run: bun install

      # Betterleaksをセットアップ
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Betterleaks scan
        run: |
          brew install betterleaks/tap/betterleaks
          betterleaks git .

      # Anti-trojan-sourceをセットアップ
      - name: Install anti-trojan-source
        run: |
          bun install anti-trojan-source
      
      - name: Anti-trojan-source scan
        run: |
          bunx anti-trojan-source --scan .